blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.gg/EVA2pznvjb
    about: For general modpack questions, gameplay help, or casual discussion, please use our Discord server instead of opening an issue.
  - name: BisectHosting
    url: https://bisecthosting.com/moderngamingworld
    about: Use code ModernGamingWorld to get 25% off first purchase
