modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
    modId="monumental_recipes"
    version="${file.jarVersion}"
    displayName="Monumental Recipes"
    description='''
        Centralizes custom crafting recipes for the Monumental Experience modpack series.
    '''

[[dependencies.monumental_recipes]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.monumental_recipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
